server:
  port: 8081
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka
      #自我保护机制
 # server:
  #  enable-self-preservation: false
 #   eviction-interval-timer-in-ms:

