spring:
 datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/si?unicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    password: sdbi
    username: root
 application:
   name: eureka-client-provider
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka #,http://127.0.0.1:8088/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1